### ISSUE TITLE
About page will not save thumbnail

### ISSUE THREAD

**Issue by ker87** [cul-it/exhibits-library-cornell-edu#117]
I am endeavoring to have this page:
https://exhibits.library.cornell.edu/vintage-vision/about/the-beginnings-of-gazette-du-bon-ton
display a thumbnail in the Page Row widget on this page:
https://exhibits.library.cornell.edu/vintage-vision

The about page thumbnail tab allows me to select an image from the exhibit and/or upload an image and provides the crop area when I do so.  However, after selecting "save" it does not save the thumbnail (returning to the thumbnail tab after navigating away shows no thumbnail present) and no thumbnail displays on the home page widget.  This functionality is correct for the feature pages.

**Comment by starsplatter** [comment]
Hi-

I'm seeing this behavior as well. I'll see if I can get it figured it out.

**Comment by starsplatter** [comment]
@cappadona This looks to me like it doesn't like saving the thumbnail parameter for pages. My transaction looks like this:

Started PATCH "/war-artifacts/about/about" for 127.0.0.1 at 2017-07-05 14:01:07 -0400
Processing by Spotlight::AboutPagesController#update as HTML
  Parameters: {"utf8"=>"✓", "authenticity_token"=>"POpl4zFjo4A02HjGNLtednOK+qT6Dkqn8cJKtAVgawq3BGqEGTul7fAZBwEW//x2WZKHHKKoEWRGfssKcjwNyA==", "about_page"=>{"title"=>"About", "content"=>"{\"data\":[{\"type\":\"text\",\"data\":{\"text\":\"<p>Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur?</p>\",\"format\":\"html\"}},{\"type\":\"featured_pages\",\"data\":{\"item\":{\"item_0\":{\"id\":\"about\",\"title\":\"About\",\"weight\":\"0\",\"display\":\"true\"}}}}]}", "published"=>"1", "thumbnail"=>{"source"=>"exhibit", "document_global_id"=>"gid://exhibits/SolrDocument/3-91", "iiif_manifest_url"=>"/war-artifacts/catalog/3-91/manifest", "iiif_canvas_id"=>"http://localhost:3000/war-artifacts/catalog/3-91/manifest/canvas/3-91", "iiif_image_id"=>"", "iiif_region"=>"1787,1116,3574,2680", "iiif_tilesource"=>"http://localhost:3000/images/103/info.json"}}, "item"=>{"item_0"=>{"id"=>"about", "title"=>"About", "weight"=>"0", "display"=>"true"}}, "document_title"=>"Soldiers of the Different Nationalities Engaged in the World War", "commit"=>"Save changes", "exhibit_id"=>"war-artifacts", "id"=>"about"}
  User Load (0.5ms)  SELECT  "users".* FROM "users" WHERE "users"."id" = ? ORDER BY "users"."id" ASC LIMIT ?  [["id", 1], ["LIMIT", 1]]
  Spotlight::Exhibit Load (0.2ms)  SELECT  "spotlight_exhibits".* FROM "spotlight_exhibits" WHERE "spotlight_exhibits"."slug" = ? LIMIT ?  [["slug", "war-artifacts"], ["LIMIT", 1]]
  Spotlight::Site Load (0.2ms)  SELECT  "spotlight_sites".* FROM "spotlight_sites" ORDER BY "spotlight_sites"."id" ASC LIMIT ?  [["LIMIT", 1]]
   (0.3ms)  SELECT COUNT(*) FROM "spotlight_roles" WHERE "spotlight_roles"."user_id" = ? AND "spotlight_roles"."role" = ? AND "spotlight_roles"."resource_type" = 'Spotlight::Site' AND "spotlight_roles"."resource_id" = 1  [["user_id", 1], ["role", "admin"]]
   (0.2ms)  SELECT "spotlight_roles"."resource_id" FROM "spotlight_roles" WHERE "spotlight_roles"."user_id" = ? AND "spotlight_roles"."resource_type" = ? AND "spotlight_roles"."role" = ?  [["user_id", 1], ["resource_type", "Spotlight::Exhibit"], ["role", "admin"]]
  CACHE (0.0ms)  SELECT "spotlight_roles"."resource_id" FROM "spotlight_roles" WHERE "spotlight_roles"."user_id" = ? AND "spotlight_roles"."resource_type" = ? AND "spotlight_roles"."role" = ?  [["user_id", 1], ["resource_type", "Spotlight::Exhibit"], ["role", "admin"]]
  CACHE (0.0ms)  SELECT "spotlight_roles"."resource_id" FROM "spotlight_roles" WHERE "spotlight_roles"."user_id" = ? AND "spotlight_roles"."resource_type" = ? AND "spotlight_roles"."role" = ?  [["user_id", 1], ["resource_type", "Spotlight::Exhibit"], ["role", "admin"]]
  Spotlight::Role Exists (0.1ms)  SELECT  1 AS one FROM "spotlight_roles" WHERE "spotlight_roles"."user_id" = ? LIMIT ?  [["user_id", 1], ["LIMIT", 1]]
   (0.1ms)  SELECT "spotlight_roles"."resource_id" FROM "spotlight_roles" WHERE "spotlight_roles"."user_id" = ? AND "spotlight_roles"."resource_type" = ?  [["user_id", 1], ["resource_type", "Spotlight::Exhibit"]]
  CACHE (0.0ms)  SELECT "spotlight_roles"."resource_id" FROM "spotlight_roles" WHERE "spotlight_roles"."user_id" = ? AND "spotlight_roles"."resource_type" = ?  [["user_id", 1], ["resource_type", "Spotlight::Exhibit"]]
  Spotlight::AboutPage Load (0.4ms)  SELECT  "spotlight_pages".* FROM "spotlight_pages" WHERE "spotlight_pages"."type" IN ('Spotlight::AboutPage') AND "spotlight_pages"."exhibit_id" = ? AND "spotlight_pages"."slug" = ? ORDER BY weight ASC LIMIT ?  [["exhibit_id", 3], ["slug", "about"], ["LIMIT", 1]]
  Spotlight::MainNavigation Load (0.2ms)  SELECT  "spotlight_main_navigations".* FROM "spotlight_main_navigations" WHERE "spotlight_main_navigations"."exhibit_id" = ? AND "spotlight_main_navigations"."nav_type" = ? ORDER BY weight ASC LIMIT ?  [["exhibit_id", 3], ["nav_type", "about"], ["LIMIT", 1]]
  Spotlight::AboutPage Load (0.4ms)  SELECT  "spotlight_pages".* FROM "spotlight_pages" WHERE "spotlight_pages"."type" IN ('Spotlight::AboutPage') AND "spotlight_pages"."exhibit_id" = ? AND "spotlight_pages"."published" = ? ORDER BY weight ASC LIMIT ?  [["exhibit_id", 3], ["published", true], ["LIMIT", 1]]
  Spotlight::Lock Load (0.2ms)  SELECT  "spotlight_locks".* FROM "spotlight_locks" WHERE "spotlight_locks"."on_id" = ? AND "spotlight_locks"."on_type" = ? LIMIT ?  [["on_id", 9], ["on_type", "Spotlight::Page"], ["LIMIT", 1]]
  SQL (1.1ms)  DELETE FROM "spotlight_locks" WHERE "spotlight_locks"."id" = ?  [["id", 19]]
Unpermitted parameter: thumbnail
   (0.1ms)  begin transaction
  FriendlyId::Slug Load (0.6ms)  SELECT  "friendly_id_slugs".* FROM "friendly_id_slugs" WHERE "friendly_id_slugs"."sluggable_id" = ? AND "friendly_id_slugs"."sluggable_type" = ? ORDER BY "friendly_id_slugs".id DESC LIMIT ?  [["sluggable_id", 9], ["sluggable_type", "Spotlight::Page"], ["LIMIT", 1]]
   (0.1ms)  commit transaction
  Spotlight::Exhibit Load (0.3ms)  SELECT  "spotlight_exhibits".* FROM "spotlight_exhibits" WHERE "spotlight_exhibits"."id" = ? LIMIT ?  [["id", 3], ["LIMIT", 1]]
  PaperTrail::Version Load (1.1ms)  SELECT  "versions".* FROM "versions" WHERE "versions"."item_id" = ? AND "versions"."item_type" = ? ORDER BY "versions"."created_at" DESC, "versions"."id" DESC LIMIT ?  [["item_id", 9], ["item_type", "Spotlight::Page"], ["LIMIT", 1]]
Redirected to http://localhost:3000/war-artifacts/about/about
Completed 302 Found in 153ms (ActiveRecord: 7.8ms)


About pages properties
 => Spotlight::AboutPage(id: integer, title: string, type: string, slug: string, scope: string, content: text, weight: integer, published: boolean, exhibit_id: integer, created_by_id: integer, last_edited_by_id: integer, created_at: datetime, updated_at: datetime, parent_page_id: integer, display_sidebar: boolean, display_title: boolean, thumbnail_id: integer) 

Search properties
 => Spotlight::Search(id: integer, title: string, slug: string, scope: string, short_description: text, long_description: text, query_params: text, weight: integer, published: boolean, exhibit_id: integer, created_at: datetime, updated_at: datetime, featured_item_id: string, masthead_id: integer, thumbnail_id: integer, default_index_view_type: string) 

Now saving browse thumbnails works, but that patch puts them in as thumbnail_attributes instead of thumbnail

  Parameters: {"utf8"=>"✓", "authenticity_token"=>"TsQV8yDYydWaICSCM1mf5nDKT6ozBtMAKWgzvj6Vp1x6sQ2QjofMOF6Bi5yUxvUlE1sbXR9OjxuIWg2e/3CskA==", "search"=>{"title"=>"Maps", "long_description"=>"", "default_index_view_type"=>"gallery", "masthead_attributes"=>{"display"=>"0", "document_global_id"=>"", "iiif_manifest_url"=>"", "iiif_canvas_id"=>"", "iiif_image_id"=>"", "iiif_region"=>"", "iiif_tilesource"=>""}, "thumbnail_attributes"=>{"source"=>"exhibit", "document_global_id"=>"gid://exhibits/SolrDocument/3-91", "iiif_manifest_url"=>"/war-artifacts/catalog/3-91/manifest", "iiif_canvas_id"=>"http://localhost:3000/war-artifacts/catalog/3-91/manifest/canvas/3-91", "iiif_image_id"=>"", "iiif_region"=>"1787,1116,3574,2680", "iiif_tilesource"=>"http://localhost:3000/images/103/info.json", "id"=>"134"}}, "document_title"=>"Soldiers of the Different Nationalities Engaged in the World War", "commit"=>"Save changes", "exhibit_id"=>"war-artifacts", "id"=>"maps"}

So I guess I need to figure out why its trying to patch thumbnail instead of thumbnail attributes on About Pages?

**Comment by starsplatter** [comment]
Okay, i have this figured out

accepts_nested_attributes_for :thumbnail, update_only: true, reject_if: proc { |attr| attr['iiif_tilesource'].blank? }

needs to get added to the about_page model.

**Comment by starsplatter** [comment]
Hi-
@ker87 this should be working now. I set a thumb nail for the Gazette page just to make sure but you should be able to go ahead and change it. Let me know if it gives you any problems. Sorry this took so long!
