### ISSUE TITLE
3.0 Validations: zoom tool buttons have wrong alt text

### ISSUE THREAD

**Issue by elrayle** [cul-it/exhibits-library-cornell-edu#508]
### Description

Reported by Craig Main in 2021-08-20 email...

> Zoom tool +/- roll-over reads "Add Circle" "Remove Circle"
> Zoom tools placed below the image would allow text to justify with images at the top. 

### Expected

Current Production: [Geological map of Syria](https://exhibits.library.cornell.edu/barazangi-map-collection/catalog/60-2733)

![image](https://user-images.githubusercontent.com/6855473/133835226-bacc5903-3ca1-4920-82a5-233ce882fcbd.png)

Hover over icons have text: Zoom In, Zoom Out, Go home, Toggle full page

### Actual

3.0 Upgrade: [Geological map of Syria](https://exhibits-prod-1.library.cornell.edu/barazangi-map-collection/catalog/60-2733)

![image](https://user-images.githubusercontent.com/6855473/133834453-2894e856-91f3-4977-96a5-e8eb2fcfb091.png)

Hover over icons have text: Add Circle, Remove Circle, Resize Small, Custom Fullscreen

**Comment by mhk33** [comment]
I looked at this and I'm not sure where the hover text is coming from for the zoom icons. Do you know, @elrayle? I looked in the spotlight and openseadragon gems.

Re: the second comment about moving the controls below -- I think this is okay as is, and I see the metadata is now displaying below the image anyway. I think there are only so many changes we want to make now in order to get the upgrade done; and we can revisit UI tweaks later.

The hover text for the icons is not great, but I also don't think it's a show stopper.
