### ISSUE TITLE
Need to be able to delete items after upload

### ISSUE THREAD

**Issue by ker87** [cul-it/exhibits-library-cornell-edu#87]
As title.  I have an erroneous image uploaded, cannot remove.

**Comment by cappadona** [comment]
Deleting items is not [currently supported by Spotlight](https://github.com/projectblacklight/spotlight/issues/843), primarily because Spotlight is intended to be used as a curation tool that allows overlaying of metadata on items from external repositories, as opposed to managing/building internal repositories directly.

Nevertheless, you're not the first to be caught off guard about not being able to delete an item that you originally uploaded directly to Spotlight (did not pull/retrieve from an external repository) -- having only the option to hide it is neither intuitive nor matches most user's expectations based on what we've observed so far.

I believe there has been discussions around this feature in the larger Spotlight community and if we were to implement something like this, we would want to do so in a way that can be contributed back to the the project.

@starsplatter You're much more familiar with this topic so please feel free to correct any misinformation here :)

**Comment by ker87** [comment]
Do we have plans for external repositories for CU exhibits?  Current "Add Items" dialog indicates no registered external repositories.

**Comment by cappadona** [comment]
@ker87 We do have plans for external repositories for CU exhibits, but we're not there yet. We do know that other Spotlight users are interested in deleting uploaded items.
