### ISSUE TITLE
On-demand snapshots of mysql and solr prior to production changes

### ISSUE THREAD

**Issue by starsplatter** [cul-it/exhibits-library-cornell-edu#98]
Is this possible - could I snapshot or backup the database and solr whenever I need to? In general, prior to deploying code to production? Or do we think nightly is close enough?

@cappadona @amccarty

**Comment by cappadona** [comment]
What's the current backup schedule for each of those?

**Comment by amccarty** [comment]
This box is backed up nightly, plus mysql gets dumped/backed up each morning early. Solr isn't explicitly backed up, though we could do that. If you want to back up pre-deploy, we could either use the filesystem- or replication-based backup method to take a snapshot...

**Comment by starsplatter** [comment]
If it is okay I think I will do

/solr/digitalcollections/replication?command=backup&numberToKeep=1

Documented here: https://cwiki.apache.org/confluence/display/solr/Making+and+Restoring+Backups

Most of the work people are doing here is stored in solr and I'm anxious to keep it safe.

**Comment by Himanshusoni9** [comment]
One More issue : On  Solr Collection Data Backup Based on Condition/Data Filter.(There is no provision for that . )

Because SOLR BACKUP API with Query is not working
//http://localhost:8983/solr/admin/collections?action=RESTORE&name=myBackupName&location=C:\Users\DELL\Downloads\SOLR_BACKUP&collection=myCondCollection&query=text:cellphone

I am trying out to perform backups of our Solr data with a particular condition in mind.

To provide some context, let's say Solr collection consists of 100 records, among which 70 records contain the text "mobile," and the remaining 30 records contain the text "cellphone." my objective is to take a Solr collection/data backup that contains only the records the text "cellphone" – essentially, we want to create a backup file that reflects these 30 specific records only.

I would greatly appreciate it if you could share insights on the best practices or methods to achieve this selective backup based on a condition. If there are specific parameters or commands we should be utilizing, kindly provide the necessary guidance. Additionally, any documentation or references you could point us to would be immensely helpful.

Thank you in advance for your time and assistance. We value your expertise and look forward to implementing an efficient solution based on your recommendations.
